# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/quickcap',
                'doc_host': 'https://tchambon.github.io',
                'git_url': 'https://github.com/tchambon/quickcap',
                'lib_path': 'quickcap'},
  'syms': {'quickcap.core': {'quickcap.core.foo': ('core.html#foo', 'quickcap/core.py')}}}
