# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/quickcap',
                'doc_host': 'https://tchambon.github.io',
                'git_url': 'https://github.com/tchambon/quickcap',
                'lib_path': 'quickcap'},
  'syms': { 'quickcap.core': { 'quickcap.core.caplogin': ('core.html#caplogin', 'quickcap/core.py'),
                               'quickcap.core.create_app': ('core.html#create_app', 'quickcap/core.py'),
                               'quickcap.core.delete_app': ('core.html#delete_app', 'quickcap/core.py'),
                               'quickcap.core.deploy': ('core.html#deploy', 'quickcap/core.py'),
                               'quickcap.core.enable_ssl': ('core.html#enable_ssl', 'quickcap/core.py'),
                               'quickcap.core.get_app_deployment_logs': ('core.html#get_app_deployment_logs', 'quickcap/core.py'),
                               'quickcap.core.get_app_logs': ('core.html#get_app_logs', 'quickcap/core.py'),
                               'quickcap.core.setup_app': ('core.html#setup_app', 'quickcap/core.py'),
                               'quickcap.core.update_app': ('core.html#update_app', 'quickcap/core.py'),
                               'quickcap.core.upload_app': ('core.html#upload_app', 'quickcap/core.py')}}}
